AFLplusplus/AFLplusplus

docs/README

Remove references to the Google CLA process.
Use new project URL.

Remove references to the Google CLA process

---

.gitignore
TODO
afl-fuzz.c
docs/env_variables.txt
qemu_mode/build_qemu_support.sh
qemu_mode/libcompcov/Makefile
qemu_mode/libcompcov/README.compcov
qemu_mode/libcompcov/libcompcov.so.c
qemu_mode/libcompcov/pmparser.h
qemu_mode/patches/afl-qemu-cpu-inl.h
qemu_mode/patches/afl-qemu-cpu-translate-inl.h
qemu_mode/patches/afl-qemu-tcg-inl.h
qemu_mode/patches/afl-qemu-translate-inl.h
qemu_mode/patches/i386-translate.diff

This merge intregrates CompareCoverage into the QEMU instrumentation.
Example command line to enable it:
`AFL_PRELOAD=~/AFLplusplus/qemu_mode/libcompcov/libcompcov.so AFL_QEMU_COMPCOV=1 ~/AFLplusplus/afl-fuzz -Q -i in -o out_cc -S slave -- ./program`
For more info refer to https://github.com/vanhauser-thc/AFLplusplus/issues/22

Qemu CompCov

---

afl-fuzz.c

```
afl-fuzz.c:4341:62: error: use of undeclared identifier 'cpu_aff'
cYEL "american fuzzy lop", use_banner, power_name, cpu_aff);
^
afl-fuzz.c:11537:7: error: use of undeclared identifier 'cpu_aff'
if (cpu_aff > 0)
^
afl-fuzz.c:11538:73: error: use of undeclared identifier 'cpu_aff'
snprintf(tmp, sizeof(tmp), "%s%d%s", "/sys/devices/system/cpu/cpu", cpu_aff, "/cpuf...
^
afl-fuzz.c:11543:9: error: use of undeclared identifier 'cpu_aff'
if (cpu_aff > 0)
^
afl-fuzz.c:11544:86: error: use of undeclared identifier 'cpu_aff'
snprintf(tmp, sizeof(tmp), "%s%d%s", "/sys/devices/system/cpu/cpufreq/policy", cpu_aff...
^
5 errors generated.
```

Unbreak build on FreeBSD

---

Makefile

If we install QEMU mode later after having already done some fuzzing runs and setting AFL_CC, QEMU mode installation will fail if AFL_CC is something else than TEST_CC.

Unset AFL_CC

---

qemu_mode/patches/syscall.diff

On Ubuntu 19.10 the QEMU mode didn't compile for me. 
The patch in this pull request (just an additional include) fixed the issue for me. This was taken from https://lists.sr.ht/~philmd/qemu/patches/6224#%3C20190617114005.24603-1-berrange@redhat.com%3E+linux-user/syscall.c
QEMU mode works for me like that.
However, the following patch is much bigger and would make it a little more robust I guess: https://patchwork.kernel.org/patch/11049817/
I didn't implement that though...
I don't know if you want to use this workaround for now or if you want to update to a newer QEMU version or whatever...

Workaround patch for QEMU

---

llvm_mode/Makefile

When using clang-8.0, The previous command in the
Makefile will get two 8.0.0, thus a warning message print.

llvm-mode: Get the clang version correctly

---

afl-system-config

The following knobs are Linux specifics but have few counterparts
in those systems.

system-config: making it more compatible with BSD systems.

---

qemu_mode/libcompcov/README.compcov
qemu_mode/libcompcov/libcompcov.so.c
qemu_mode/patches/afl-qemu-cpu-inl.h
qemu_mode/patches/afl-qemu-cpu-translate-inl.h
qemu_mode/patches/i386-translate.diff

Now the env var AFL_COMPCOV_LEVEL tells QEMU and libcompcov how to log comaprisons.
Level 1 logs just comparisons with immediates / read-only memory and level 2 logs all the comparisons as the previous version of QEMU compcov.
AFL_QEMU_COMPCOV is now an alias for AFL_COMPCOV_LEVEL=1 when AFL_COMPCOV_LEVEL is not specified.

compcov levels to enable the instrumentation of only comparisons with immediates

---

qemu_mode/patches/afl-qemu-cpu-translate-inl.h
qemu_mode/patches/afl-qemu-translate-inl.h
unicorn_mode/patches/afl-unicorn-cpu-inl.h
unicorn_mode/patches/afl-unicorn-tcg-runtime-inl.h

@andreafioraldi this fixes the SIGSEV in your current branch. 
It happened when the pointer was close to `MAP_SIZE` as it would try to read multiple bytes (out of bounds)
When it comes to memory safety, assembler is not much better than c :D
Thix fixes the issue discussed in #50

Fixed SIGSEV due to wrong pointer size

---

src/afl-fuzz-one.c

Custom fuzzer module seems to be repeatedly getting the output buffer as sample data instead of the original sample data. This leads to crashes and generally poor results.

use the original data as input to custom fuzzer modules

---

Makefile
README.md
qemu_mode/README.md
qemu_mode/build_qemu_support.sh
src/afl-fuzz-run.c

These are changes that should help with fuzzing closed-source embedded devices.
* Adds support for statically compiling both AFL and QEMU binaries
* Improved error message when unable to reach the fork server
* Related documentation updates

Build statically-linked binaries

---

src/afl-fuzz.c

This fixes a minor incovenience:
When running unicorn mode, we will usually call the python interpreter as actual binary.
This may point to the python in the PATH, which is correct. No need to nag the user :)

No Longer Warns for Absolute Binaries for Unicorn

---

libtokencap/Makefile
libtokencap/libtokencap.so.c

Avoiding fopen API seems buggy on NetBSD.

Fix proposal for libtokencap

---

libtokencap/libtokencap.so.c

is non C standard, some compilers might not have GNU extensions.

libtokencap, respect constness also considering pointer arithmetic

---

libtokencap/libtokencap.so.c
llvm_mode/afl-clang-fast.c
src/afl-gcc.c

- bcmp interception.
- FreeBSD using default argument to get current pid for the mapping
data gathering, getpid seems to cause some issues under certain
conditions (getenv call).

libtokencap update proposal

---

llvm_mode/Makefile
llvm_mode/afl-clang-fast.c

On FreeBSD the system compiler does not have llvm-config
however system packages provides several version of the
LLVM toolchain thus forcing to pass AFL_CC/AFL_CXX to make
it work fully.

LLVM mode passing the full path of the LLVM config bindir.

---

gcc_plugin/Makefile
gcc_plugin/README.gcc.md
gcc_plugin/afl-gcc-fast.c

like its llvm counterpart, passing the compiler chain used
to avoid using necessarily AFL_CC/AFL_CXX.

gcc plugin little update proposal.

---

unicorn_mode/build_unicorn_support.sh

When building on macOS I get the following error:
```
[*] Info: Installing python unicorn using --user
running install
error: can't combine user with prefix, exec_prefix/home, or install_(plat)base
make: *** [osx-only] Error 1
```
Which relates to the following line of the build script [Line 201](https://github.com/vanhauser-thc/AFLplusplus/blob/master/unicorn_mode/build_unicorn_support.sh#L201):
```sh
$PYTHONBIN setup.py install --user || exit 1
```
It seems to be a known problem (https://stackoverflow.com/questions/4495120/combine-user-with-prefix-error-with-setup-py-install) which can be fixed by passing `--prefix=` option to the `setup.py` invocation. 
Tested on: macOS Catalina 10.15 / Python 2.7.15 (default, Feb  1 2019, 09:46:00)

Fix unicorn build error on macOS

---

llvm_mode/LLVMInsTrim.so.cc
llvm_mode/Makefile

c++14 is the minimum for this version, thus the hardcoded gnu++11
standard flag makes the build fails.
Missing header only for this version seemingly for the option.

LLVM 10 build fix proposal

---

qemu_mode/build_qemu_support.sh
unicorn_mode/build_unicorn_support.sh

because of QEMU not supported.
Symplifying cores counting data gathering.

On non Linux systems, (g)make distrib stops halfway

---

llvm_mode/Makefile

plus cleanup of the unicorn submodule.
I'm not sure if the version checking logic in llvm_mode/Makefile still makes sense after 123d97bfb896aefca24ff8bdc235b900fe714fde - but at least it should use the same llvm-config.

minor fix for llvm_mode build with non-standard paths

---

Makefile
experimental/argv_fuzzing/Makefile
experimental/argv_fuzzing/README.md
experimental/argv_fuzzing/argvfuzz.c

LD_PRELOAD library, hooks `__libc_start_main` to replace `argv` with data from stdin (uses logic from `argv-fuzz-impl.h`).
Instead of hooking __libc_start_main, a more generic approach might be to provide a `__attribute__((constructor))` function which also gets argc, argv and envp as arguments. However - unless I've missed something - such a function would not be able to change them without doing stack unwinding (see e.g., https://sourceware.org/git/?p=glibc.git;a=blob;f=sysdeps/x86_64/dl-machine.h;h=58260c7876fd361a5a6f30e11a341ceb605a199c;hb=HEAD#l141)

argvfuzz preload for fuzzing binaries' argv

---

src/afl-fuzz-python.c

retbuf gets malloced in 'trim_py', however, it's never freed afterwards in 'trim_case_python'.

Fixed memory leak in afl-fuzz-python.c - trim_case_python.

---

llvm_mode/afl-llvm-pass.so.cc

avoiding intrinsics generated by LLVM for the instrumentation.

llvm_mode little update proposal.

---

Makefile
docs/python_mutators.txt
src/afl-fuzz.c

This fixes #182 and should(tm) work on major operating systems (as long as Python is in the PATH).
Maybe someone can check on BSDs if it works there as expected, too, before merging into master

Broader Python Support

---

llvm_mode/afl-clang-fast.c

Support to ubsan in afl-clang-fast. I choosed the `-fsanitize=undefined -fsanitize-undefined-trap-on-error -fno-sanitize-recover=all` flags, should be correct.

add AFL_USE_UBSAN

---

README.md
src/afl-fuzz.c

If we let multiple fuzzers end with -V or -E option, it will cause it to think we are still occupying the cores, even if they are free, once we try to run another job it would return an error that no free nodes are available.
This change fixes that problem.

Fix hanging fork and child with -V -E

---

README.md

This dependency appears to be required for UnicornAFL.  Running the previous apt command ad then `make distrib` on a clean Debian 10 install should reproduce the issue.  The sanity checks did work and very helpfully pointed me to the package, but I figured it should be listed here too. :smiley:

Added missing dependency to the documnetation. Tested on Debian 10

---

examples/custom_mutators/example.c

This example doesn't compile due to two little errors:
- There is a missing semicolon
- "data" array doesn't exist. I think "buf" should be used instead.

Fixing 2 little mistakes

---

qemu_mode/patches/afl-qemu-cpu-translate-inl.h

When running persistent qemu-mode with CPU_TARGET=i386 on x86_64 host like this:
```sh
AFL_DEBUG_CHILD_OUTPUT=1 AFL_QEMU_PERSISTENT_ADDR=$function_start_addr afl-fuzz -Q -i in -o out -- ./test @@
```
afl aborts with message:
/AFLplusplus/qemu_mode/qemu-3.1.1/tcg/tcg-op.c:2646: tcg fatal error
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
This patch fixes the error

fix qemu persistent mode for 32-bit target on 64-bit host

---

.gitignore
docs/custom_mutators.md
examples/custom_mutators/example.c
examples/custom_mutators/example.py
include/afl-fuzz.h
src/afl-fuzz-mutators.c
src/afl-fuzz-one.c
src/afl-fuzz-python.c
src/afl-fuzz-queue.c

- `afl_custom_queue_get` is added before checking `pending_favored`
- `afl_custom_queue_new_entry` is added at the end of `add_to_queue`
- Update the corresponding document and examples
- Update `.gitignore` to exclude `afl-clang-lto`, `afl-clang-lto++`, `afl-clang-lto.8`, and `afl-clang-lto++.8`

Two new hooks for the custom mutator

---

afl-whatsup

Fixes #197 
Now afl-whatsup also prints time since the most recent path has been found across all synchronized afl-fuzz instances.
One can then do some greps to check if required time has passed to perform some actions.
Example:
```
afl-whatsup out | grep "Time without finds: 3 hours"
```

add "time without finds" to afl-whatsup

---

llvm_mode/afl-llvm-lto-instrumentation.so.cc

seems to be available even on LLVM 3.7

llvm_mode: using MaybeAlign wrapper over the deprecated setter.

---

GNUmakefile
src/afl-fuzz-extras.c
src/afl-showmap.c

LTO flag is recognised but however broken on Android (tested with armv7 arch).
Thus giving the choice not to enable it.
In fortify mode, open required O_CREAT or O_TMPFILE when mode is set.

Android build fix proposal.

---

examples/crash_triage/triage_crashes.sh

The script uses an otherwise unused variable to collect the arguments for the target and thus always executes it without arguments

fixes crash triage example

---

qbdi_mode/build.sh

Hi,
the `build.sh` script was failing to build `afl-fuzz` for Android due to missing source files:
```
Ξ pyno(fearless) qbdi_mode git:(master) ▶ STANDALONE_TOOLCHAIN_PATH=/fuzz/android/android-ndk-r21/toolchains/llvm/prebuilt/linux-x86_64 QBDI_SDK_PATH=/fuzz/code/AFLplusplus/qbdi_mode/android-qbdi-sdk-x86_64/ CC=x86_64-linux-android29-clang CXX=x86_64-linux-android29-clang++ ./build.sh x86_64
build x86_64 qbdi
[+] Building the QBDI template
[+] Building the demo library
[+] Building afl-fuzz for Android
clang: error: no such file or directory: 'src/afl-fuzz-misc.c'
[+] All done. Enjoy!
```
I have fixed by modifying the related line to include `src/afl-fuzz-*.c` instead of specifying single files to be compiled.
Hope this helps,
pyno

Fixed qbdi_mode/build.sh script

---

llvm_mode/afl-clang-fast.c

I'm not too sure about the specific error message, but this may be helpful when someone is trying to do things with the filename, such as wrapping it in an `exec` script. Another solution might be to generate a warning here, but doing nothing might make people shoot themselves in the foot.
In my case, the program was wrapped in a script that setup some environment stuff. Because the script called `exec`, the program name was the name of the script. Trying to compile c++ binaries failed because the c compiler was invoked (the `else` branch was used), resulting in errors like `fatal error: 'new' file not found`. Generating a failure or warning because the wrong compiler might be invoked seems like a valid choice.
Ultimately, the aforementioned script is unnecessary after applying the …

afl-clang-fast: fail when binary name can't be used to determine build mode

---

gcc_plugin/afl-gcc-fast.c
src/afl-gcc.c

This is a continuation of PR #318.
The goal is to prevent issues where binaries with the wrong name will
silently pass control to the C compiler instead of failing.
This makes it more explicit that aflplusplus relies on the name of the
binary for correct compiler execution.

afl-gcc and afl-clang: fail when binary name can't be used to determine build mode

---

include/types.h
src/afl-fuzz-one.c

Some changes were made in src/afl-fuzz-one.c and types.h . A primary report on fuzzer  performance, before and after patching is given below.
| Details   |                                                    |
|-------------|-------------------------------------------|
| OS          | Ubuntu Bionic |
| System   | Google Compute N1 custom (10 vCPUs, 9 GB memory) [ Free Tier ] |
| Test Lib   |   Binutils-2.30 |
The binaries were compiled using afl-clang-fast.
The command line argument used is ::
`` $ afl-fuzz -i afl_in -o afl_o_# -d -V 43200 # $ @@ ``
Each binutil was fuzzed only once using patched and unpatched afl-fuzz-one.c .
* where # stands for the following binutils used
* where $ stands for the arguments used along with them
|    #    |    $    |
|---------|---------|
| readelf |   -a …

Integer-Swapping Havoc Mutator

---

.gitignore
unicorn_mode/build_unicorn_support.sh

Hi, I recently tried to build Unicorn mode support for AFL++ from my WSL distribution (Ubuntu-18.04). Unfortunately, the Unicorn build script repeatedly failed because it couldn't generate the test harness, but after applying the suggested changes it managed to compile and run successfully. Hope that helps 😅

Fix Unicorn support build script

---

README.md

Building `make distrib` on a clean Ubuntu install, after installing dependencies `sudo apt install build-essential libtool-bin python3 automake bison libglib2.0-dev libpixman-1-dev clang python-setuptools llvm`, yielded the following error during build:
```
cd qemu_mode && sh ./build_qemu_support.sh
=================================================
AFL binary-only instrumentation QEMU build script
=================================================
[*] Performing basic sanity checks...
[-] Error: 'flex' not found, please install first.
GNUmakefile:467: recipe for target 'distrib' failed
make: *** [distrib] Error 1
```
`sudo apt install flex` resolved this build issue. Therefore, this PR adds flex to the build instructions.

add flex to apt install list

---

docs/custom_mutators.md
examples/custom_mutators/example.c
examples/custom_mutators/example.py
examples/post_library/post_library.so.c
examples/post_library/post_library_png.so.c
include/afl-fuzz.h
src/afl-fuzz-cmplog.c
src/afl-fuzz-init.c
src/afl-fuzz-mutators.c
src/afl-fuzz-python.c
src/afl-fuzz-run.c
src/afl-fuzz-state.c

Renamed pre_save to something better.
Used the POST library api as a custom mutator since now we can support multiple custom mutators

Add post library API as custom mutator and rename pre_save

---

llvm_mode/compare-transform-pass.so.cc
test/test-compcov.c
test/test.sh

Don't know if this is of any use to you, but I've been using this modification with some success.
Some targets use sized comparisons with non-const `n` values (in cases I've seen this is usually the length of the variable-string's buffer). These can be handled by insertion of a "length check" bb for each unrolled character, branching to the phi node with a zero return value if the n argument equals each character's position index.
To make this easier to tackle I did a bit of refactoring of the length determination and renaming of variables.
And to give myself more confidence that I'm not breaking any of this existing logic I added some extra cases to `test-compcov.c` and extra steps to `test.sh` that actually test the correctness of the resulting binary's behaviour, also adding calls to …

llvm_mode compare-transform-pass: add handling of sized comparisons with non-const size

---

llvm_mode/afl-clang-fast.c

When compiling the following minimal C++ fuzzing target test.cpp for LLVM's Persistent Mode
```
#include <stdlib.h>
__AFL_FUZZ_INIT();
int main(int argc, char **argv) {
unsigned char *buffer = __AFL_FUZZ_TESTCASE_BUF;
}
```
with afl-clang-fast++, the compilation will fail with this error:
```
afl-clang-fast++2.65d by <lszekeres@google.com> in PCGUARD mode
test.cpp:6:29: error: assigning to 'unsigned char *' from incompatible type 'void *'
unsigned char *buffer = __AFL_FUZZ_TESTCASE_BUF;
^~~~~~~~~~~~~~~~~~~~~~~
<command line>:5:90: note: expanded from here
#define __AFL_FUZZ_TESTCASE_BUF (__afl_fuzz_ptr ? __afl_fuzz_ptr : (__afl_fuzz_alt_ptr = malloc(1 * 1024 * 1024)))
^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```
The problem seems to be the decleration of `__afl_fuzz_alt_ptr` in Line …

Fixed missing cast in afl-clang-fast.c, which results in a compilation error when using __AFL_FUZZ_TESTCASE_BUF in a C++ target

---

src/afl-fuzz-bitmap.c

Since during normal fuzzing, crash_mode is FSRV_RUN_OK, and fault is also usually FSRV_RUN_OK since most executions are valid executions, thus it should be likely instead of unlikely

`fault == afl->crash_mode` should be likely

---

test/test.sh

I don't advocate having spaces in a directory name, but this change should fix test/test.sh in that case.
By the way, is the travis CI status visible somewhere? afl-fuzz -R (radamsa) somehow stopped working on my machine, and it would be useful to know whether it's a local issue or if something might've broken in the code tree.

Fix when env. PATH contains spaces

---

src/afl-fuzz-run.c

I have observed two problems:
1. A sudden "stability cliff" where stability drops precipitously.
2. A sudden jump to a 100% saturated "density map".
I tracked both issues down to the attempted "recalibrations" of a case
at the beginnings of fuzz_one_original() and mopt_common_fuzzing().
See the comments "CALIBRATION (only if failed earlier on)" in those
functions and the subsequent call to calibrate_case().
At those two calls to calibrate_case(), afl->fsrv.trace_bits holds
trace_bits for a previous run of the SUT for a prior queue entry.
However, calibrate_case() may use the trace_bits as if they apply to
the current queue entry (afl->queue_cur).
Most often this bug causes the "stability cliff".  Trace bits are
compared for runs on completely different inputs and there are a lot
of …

Fix saturated maps & stability cliff in recalibration

---

GNUmakefile

When a reproducible distribution build is wanted,
it is not good to make build results depend on the build machine's CPU
There might be other good ways to fix this?
See https://reproducible-builds.org/ for why this matters.
This PR was done while working on reproducible builds for openSUSE.

Dont always use march=native

---

llvm_mode/afl-llvm-rt.o.c

MAP_EXCL|MAP_FIXED is a (genuine) equivalent to Linux's MAP_FIXED_NOREPLACE.

llvm mode shared segment fix for FreeBSD.
