AFLplusplus/AFLplusplus

llvm_mode/compare-transform-pass.so.cc, llvm_mode/split-switches-pass.so.cc
```
// compile with:                                                                                                                                                                                                                  
// LAF_SPLIT_SWITCHES=1 LAF_TRANSFORM_COMPARES=1 LAF_SPLIT_COMPARES=1 AFL_HARDEN=1 .../AFLplusplus/afl-clang-fast test.c -o test                                                                                                  
#include <stdio.h>                                                                                                                                                                                                                
#include <string.h> …
```
=> Fix crashes

afl-fuzz.c
Solution not involving file descriptors, seeded upon fork and on a regular basis.
This was done by @devnexen in https://github.com/google/AFL/pull/8. I only rebased it. I am hoping it can find a home here.
=> Use arc4random(3) on *BSD/macOS

Android.mk, afl-analyze.c, afl-fuzz.c, afl-gotcpu.c, afl-showmap.c, afl-tmin.c, afl-whatsup, android-ashmem.h, llvm_mode/afl-llvm-pass.so.cc, llvm_mode/afl-llvm-rt.o.c, sharedmem.c
Orig from android-afl,
Example to build this for android using llvm:
export AFL_TRACE_PC=true
mm
Example to enable android-test with afl:
cd android-test
TEST_CLANG_FAST_AARCH64=true mm
=> Port for Android

src/afl-fuzz-init.c
Checking optimal cpu performance or ignore if the AFL_SKIP_CPUFREQ
env is set.
=> Checking CPU scaling on MacOS

docs/ChangeLog, qemu_mode/build_qemu_support.sh, qemu_mode/patches/afl-qemu-common.h, qemu_mode/patches/afl-qemu-cpu-inl.h, qemu_mode/patches/afl-qemu-cpu-translate-inl.h, qemu_mode/patches/arm-translate.diff, unicorn_mode/patches/compcov.diff
Implements CompCov for at least the ARM QEMU target
=> Multiarch CompCov

libtokencap/Makefile, libtokencap/libtokencap.so.c
Reading only main addresses and read only's.
=> Porting libtokencap to Darwin.

include/afl-fuzz.h, src/afl-fuzz-init.c, src/afl-gotcpu.c
Thanks their API is very similar in this area.
=> Porting cpu affinity to DragonFly.

src/third_party/libradamsa/libradamsa.c
Note: do not know if it should be upstreamed first or not though...
=> libradamsa forgotten possible undefined symbol.

src/afl-fuzz.c
when killed or for a defined amount of time.
=> the plot data does not generate proper gnuplot data

libdislocator/libdislocator.so.c
- optional tls alloc_canary value.
- slight change of memory limit value checking.
=> libdislocator updates improvements proposal.

include/afl-fuzz.h, src/afl-fuzz-bitmap.c, src/afl-fuzz-init.c
system call is disabled on this platform.
=> IOS build fix.

unicorn_mode/samples/compcov_x64/compcov_test_harness.py, unicorn_mode/samples/simple/simple_test_harness.py
This PR removes unneeded code from the python examples and fixes a tiny bug in uc_afl_fuzz where files would not be unmapped.
=> Tidied up python examles and fixed bug in uc_afl_fuzz

libtokencap/libtokencap.so.c
Incrementing base address for next iteration.
=> libtokencap, fix mac os process map lookup.

src/afl-fuzz-globals.c
Fix env var types assignments.
=> Just compute the current len once.

src/afl-fuzz-stats.c
Just a code formatting commit. :sweat_smile:
=> Code Format

libdislocator/libdislocator.so.c
Bionic libc has different signature for this one.
=> libdislocator android build fix.

docs/Changelog.md, llvm_mode/afl-llvm-common.cc, src/afl-fuzz-run.c
mainly for the older llvm version fix
=> dev -> master

examples/afl_network_proxy/afl-network-client.c
=> Build fix proposal mainly for Android which did not bother

dictionaries/perl.dict
As part of my continuous fuzzing with `AFL`. I utilized some common functions for fuzzing basic I/O in `perl5`. Hope this helps others while fuzzing `perl5`. I'll keep updating this dictionary in future.
=>  Grammar for fuzzing Perl

unicorn_mode/samples/persistent/harness.c
Signed-off-by: Toralf Förster <toralf.foerster@gmx.de>
=> unicorn_mode/samples/persistent/harness.c: fix comment

GNUmakefile, gcc_plugin/GNUmakefile, gcc_plugin/afl-gcc-fast.c, gcc_plugin/afl-gcc-rt.o.c, include/afl-fuzz.h, llvm_mode/GNUmakefile, llvm_mode/afl-clang-fast.c, src/afl-analyze.c, src/afl-fuzz-stats.c, src/afl-gcc.c, src/afl-sharedmem.c, src/afl-showmap.c, src/afl-tmin.c, src/third_party/libradamsa/libradamsa.c
getrusage does not implement resident memory gathering, no shm api neither.
=> Porting to Haiku.
